//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopManager.ProjectResources.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShopManager.ProjectResources.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap app {
            get {
                object obj = ResourceManager.GetObject("app", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رصيد أول المدة.
        /// </summary>
        public static string BeginninBalance {
            get {
                return ResourceManager.GetString("BeginninBalance", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap browse {
            get {
                object obj = ResourceManager.GetObject("browse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Icon building {
            get {
                object obj = ResourceManager.GetObject("building", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Bitmap clean {
            get {
                object obj = ResourceManager.GetObject("clean", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرصيد الحالي.
        /// </summary>
        public static string CurrentBalance {
            get {
                return ResourceManager.GetString("CurrentBalance", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap database {
            get {
                object obj = ResourceManager.GetObject("database", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap database_add {
            get {
                object obj = ResourceManager.GetObject("database_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap database_import {
            get {
                object obj = ResourceManager.GetObject("database_import", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap databaserefresh {
            get {
                object obj = ResourceManager.GetObject("databaserefresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap delete1 {
            get {
                object obj = ResourceManager.GetObject("delete1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap eject {
            get {
                object obj = ResourceManager.GetObject("eject", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap filter {
            get {
                object obj = ResourceManager.GetObject("filter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رصيد أول المدة.
        /// </summary>
        public static string FridgeStoragesControl_SupplierComboBoxValidated_BeginningBalance {
            get {
                return ResourceManager.GetString("FridgeStoragesControl_SupplierComboBoxValidated_BeginningBalance", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap Icon_238 {
            get {
                object obj = ResourceManager.GetObject("Icon_238", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap info {
            get {
                object obj = ResourceManager.GetObject("info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap info2 {
            get {
                object obj = ResourceManager.GetObject("info2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap insert {
            get {
                object obj = ResourceManager.GetObject("insert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap loading {
            get {
                object obj = ResourceManager.GetObject("loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...جاري الإرسال.
        /// </summary>
        public static string Main_sendErrorReportEmailToolStripButton_Click____جاري_الإرسال {
            get {
                return ResourceManager.GetString("Main_sendErrorReportEmailToolStripButton_Click____جاري_الإرسال", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسل تقرير الأخطاء.
        /// </summary>
        public static string Main_SendReportBackgroundWorkerRunWorkerCompleted_ارسل_تقرير_الأخطاء {
            get {
                return ResourceManager.GetString("Main_SendReportBackgroundWorkerRunWorkerCompleted_ارسل_تقرير_الأخطاء", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap OFFOWC_DLL_23 {
            get {
                object obj = ResourceManager.GetObject("OFFOWC_DLL_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap OFFOWC_DLL_25 {
            get {
                object obj = ResourceManager.GetObject("OFFOWC_DLL_25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap OFFOWC_DLL_79 {
            get {
                object obj = ResourceManager.GetObject("OFFOWC_DLL_79", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorLogFile(ErrorLog.txt)|ErrorLog.txt.
        /// </summary>
        public static string ParentControl_CopyErrorReportTo_ErrorLogFile_ErrorLog_txt__ErrorLog_txt {
            get {
                return ResourceManager.GetString("ParentControl_CopyErrorReportTo_ErrorLogFile_ErrorLog_txt__ErrorLog_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سيتم حذف جميع البيانات بالجدول و كل ما يتعلق بها. هل أنت متأكد؟ .
        /// </summary>
        public static string ParentControl_DeleteAllData {
            get {
                return ResourceManager.GetString("ParentControl_DeleteAllData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد حذف البيانات.
        /// </summary>
        public static string ParentControl_DeleteAllData_تأكيد_حذف_البيانات {
            get {
                return ResourceManager.GetString("ParentControl_DeleteAllData_تأكيد_حذف_البيانات", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل تريد الإدخال/التحديث الآن؟.
        /// </summary>
        public static string ParentControl_InsertEditPanelValidating_ {
            get {
                return ResourceManager.GetString("ParentControl_InsertEditPanelValidating_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Cancel)أريد تعديل البيانات.
        /// </summary>
        public static string ParentControl_InsertEditPanelValidating__Cancel_أريد_تعديل_البيانات {
            get {
                return ResourceManager.GetString("ParentControl_InsertEditPanelValidating__Cancel_أريد_تعديل_البيانات", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (No)أريد حذفها.
        /// </summary>
        public static string ParentControl_InsertEditPanelValidating__No_أريد_حذفها {
            get {
                return ResourceManager.GetString("ParentControl_InsertEditPanelValidating__No_أريد_حذفها", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (yes)أريد الإدخال/التحديث الآن.
        /// </summary>
        public static string ParentControl_InsertEditPanelValidating__yes_أريد_الإدخال_التحديث_الآن {
            get {
                return ResourceManager.GetString("ParentControl_InsertEditPanelValidating__yes_أريد_الإدخال_التحديث_الآن", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوجد بيانات.
        /// </summary>
        public static string ParentControl_InsertEditPanelValidating_يوجد_بيانات {
            get {
                return ResourceManager.GetString("ParentControl_InsertEditPanelValidating_يوجد_بيانات", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوجد بيانات بالصفحة .
        /// </summary>
        public static string ParentControl_InsertEditPanelValidating_يوجد_بيانات_بالصفحة_ {
            get {
                return ResourceManager.GetString("ParentControl_InsertEditPanelValidating_يوجد_بيانات_بالصفحة_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الكود موجود مسبقا.
        /// </summary>
        public static string ParentControl_ParentDataGridViewDataError_هذا_الكود_موجود_مسبقا {
            get {
                return ResourceManager.GetString("ParentControl_ParentDataGridViewDataError_هذا_الكود_موجود_مسبقا", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد حذف سجل.
        /// </summary>
        public static string ParentControl_ParentDataGridViewUserDeletingRow_تأكيد_حذف_سجل {
            get {
                return ResourceManager.GetString("ParentControl_ParentDataGridViewUserDeletingRow_تأكيد_حذف_سجل", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إرسال التقرير بنجاح.
        /// </summary>
        public static string ParentControl_SendErrorReportEmail_تم_إرسال_التقرير_بنجاح {
            get {
                return ResourceManager.GetString("ParentControl_SendErrorReportEmail_تم_إرسال_التقرير_بنجاح", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم الإرسال تأكد من اتصالك بالإنترنت.
        /// </summary>
        public static string ParentControl_SendErrorReportEmail_لم_يتم_الإرسال_تأكد_من_اتصالك_بالإنترنت {
            get {
                return ResourceManager.GetString("ParentControl_SendErrorReportEmail_لم_يتم_الإرسال_تأكد_من_اتصالك_بالإنترنت", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to write a log.
        /// </summary>
        public static string ParentControl_WriteToLog_Unable_to_write_a_log {
            get {
                return ResourceManager.GetString("ParentControl_WriteToLog_Unable_to_write_a_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string PrintDGV_PrintDoc_PrintPage_Error {
            get {
                return ResourceManager.GetString("PrintDGV_PrintDoc_PrintPage_Error", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap qmark {
            get {
                object obj = ResourceManager.GetObject("qmark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Refresh {
            get {
                object obj = ResourceManager.GetObject("Refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الثلاجة.
        /// </summary>
        public static string ReportViewerControl_ShowFridgesStoragesReport_FridgeName {
            get {
                return ResourceManager.GetString("ReportViewerControl_ShowFridgesStoragesReport_FridgeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كل العصير.
        /// </summary>
        public static string ReportViewerControl_ShowSalesN_CagesReport_AllJuice {
            get {
                return ResourceManager.GetString("ReportViewerControl_ShowSalesN_CagesReport_AllJuice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم العميل.
        /// </summary>
        public static string ReportViewerControl_ShowSalesN_CagesReport_clientName {
            get {
                return ResourceManager.GetString("ReportViewerControl_ShowSalesN_CagesReport_clientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع العصير.
        /// </summary>
        public static string ReportViewerControl_ShowSalesN_CagesReport_juiceType {
            get {
                return ResourceManager.GetString("ReportViewerControl_ShowSalesN_CagesReport_juiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كل الخام.
        /// </summary>
        public static string ReportViewerControl_ShowSelectPurchaseReport_AllRaw {
            get {
                return ResourceManager.GetString("ReportViewerControl_ShowSelectPurchaseReport_AllRaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الخام.
        /// </summary>
        public static string ReportViewerControl_ShowSelectPurchaseReport_RawType {
            get {
                return ResourceManager.GetString("ReportViewerControl_ShowSelectPurchaseReport_RawType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المورد.
        /// </summary>
        public static string ReportViewerControl_ShowSelectPurchaseReport_SupplierName {
            get {
                return ResourceManager.GetString("ReportViewerControl_ShowSelectPurchaseReport_SupplierName", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap sendemail {
            get {
                object obj = ResourceManager.GetObject("sendemail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap sidebar {
            get {
                object obj = ResourceManager.GetObject("sidebar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap view {
            get {
                object obj = ResourceManager.GetObject("view", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
