//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShopManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جاري تحميل .
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  صف.
        /// </summary>
        internal static string Main_OutputNumberOfrowsChanged__Row {
            get {
                return ResourceManager.GetString("Main_OutputNumberOfrowsChanged__Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يعرض الآن .
        /// </summary>
        internal static string Main_OutputNumberOfrowsChanged_ShowingNow {
            get {
                return ResourceManager.GetString("Main_OutputNumberOfrowsChanged_ShowingNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - .
        /// </summary>
        internal static string Main_OutputTimeRangeChanged__Separator {
            get {
                return ResourceManager.GetString("Main_OutputTimeRangeChanged__Separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أد&amp;خل.
        /// </summary>
        internal static string Main_ParentControlClearData_Insert {
            get {
                return ResourceManager.GetString("Main_ParentControlClearData_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت العملية بنجاح.
        /// </summary>
        internal static string Main_ParentControlItemSuccessfullySubmitted_DoneSuccessfuly {
            get {
                return ResourceManager.GetString("Main_ParentControlItemSuccessfullySubmitted_DoneSuccessfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ع&amp;دل.
        /// </summary>
        internal static string Main_ParentControlRowEnter_Modify {
            get {
                return ResourceManager.GetString("Main_ParentControlRowEnter_Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جاهز.
        /// </summary>
        internal static string Main_Ready {
            get {
                return ResourceManager.GetString("Main_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد تقرير.
        /// </summary>
        internal static string Main_sendErrorReportEmailToolStripButton_Click_لا_يوجد_تقرير {
            get {
                return ResourceManager.GetString("Main_sendErrorReportEmailToolStripButton_Click_لا_يوجد_تقرير", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لاختيار قسم : اضغط Ctrl+ ترتيب القسم.
        /// </summary>
        internal static string Main_ShowKeyBoardHelp_HowToSelectASection {
            get {
                return ResourceManager.GetString("Main_ShowKeyBoardHelp_HowToSelectASection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ أثناء التنفيذ.
        /// </summary>
        internal static string MainInstaller_ExecuteSql_ErrorInExecution {
            get {
                return ResourceManager.GetString("MainInstaller_ExecuteSql_ErrorInExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التنفيذ بنجاح.
        /// </summary>
        internal static string MainInstaller_ExecuteSql_ExecutedwithSuccess {
            get {
                return ResourceManager.GetString("MainInstaller_ExecuteSql_ExecutedwithSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Cancel) عدم فعل أي شئ .
        /// </summary>
        internal static string Program_Main__Cancel_DoNothing {
            get {
                return ResourceManager.GetString("Program_Main__Cancel_DoNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (No) نسخ تقرير الأخطاء إلى ملف.
        /// </summary>
        internal static string Program_Main__No__CopyToAFile {
            get {
                return ResourceManager.GetString("Program_Main__No__CopyToAFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Yes) إرسال تقرير الأخطاء عن طريق النت.
        /// </summary>
        internal static string Program_Main__Yes__SendReportOnline {
            get {
                return ResourceManager.GetString("Program_Main__Yes__SendReportOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ !!.
        /// </summary>
        internal static string Program_Main_ErrorOccured {
            get {
                return ResourceManager.GetString("Program_Main_ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث الخطأ التالي : .
        /// </summary>
        internal static string Program_Main_FollowingErrorHappened {
            get {
                return ResourceManager.GetString("Program_Main_FollowingErrorHappened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  هل تريد إعادة تشغيل البرنامج؟ .
        /// </summary>
        internal static string Program_Main_ProgramWillBeRestarted {
            get {
                return ResourceManager.GetString("Program_Main_ProgramWillBeRestarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن تشغيل أكثر من نسخة من البرنامج..
        /// </summary>
        internal static string Program_Main_UseOnlyOneInstance {
            get {
                return ResourceManager.GetString("Program_Main_UseOnlyOneInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ماذا تريد أن تفعل ؟.
        /// </summary>
        internal static string Program_Main_WhatToDo {
            get {
                return ResourceManager.GetString("Program_Main_WhatToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جاري عمل حفظ تلقائي.
        /// </summary>
        internal static string StartUpWizard_InitializeNormal_DoingAnAutomaticBackup {
            get {
                return ResourceManager.GetString("StartUpWizard_InitializeNormal_DoingAnAutomaticBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحفظ الاحتياطي لقاعدة البيانات.
        /// </summary>
        internal static string StartUpWizard_Loading_Shown_DatabaseBackup {
            get {
                return ResourceManager.GetString("StartUpWizard_Loading_Shown_DatabaseBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل تريد حفظها الآن؟.
        /// </summary>
        internal static string StartUpWizard_Loading_Shown_SaveNow {
            get {
                return ResourceManager.GetString("StartUpWizard_Loading_Shown_SaveNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم الإرسال تأكد من اتصالك بالإنترنت.
        /// </summary>
        internal static string StartUpWizard_sendInfoBackgroundWorker_RunWorkerCompleted_NoInternet {
            get {
                return ResourceManager.GetString("StartUpWizard_sendInfoBackgroundWorker_RunWorkerCompleted_NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إرسال المعلومات بنجاح.
        /// </summary>
        internal static string StartUpWizard_sendInfoBackgroundWorker_RunWorkerCompleted_SendingSucceeded {
            get {
                return ResourceManager.GetString("StartUpWizard_sendInfoBackgroundWorker_RunWorkerCompleted_SendingSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...جاري الإرسال.
        /// </summary>
        internal static string StartUpWizard_sendInfoIDButton_Click_Sending {
            get {
                return ResourceManager.GetString("StartUpWizard_sendInfoIDButton_Click_Sending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  كلمة سر البدء و تأكيدها غير متطابقتين أو إحداهما فارغه !!.
        /// </summary>
        internal static string StartUpWizard_startButton_Click__PasswordAndConfirmationNotMatchingOrOneIsEmpty {
            get {
                return ResourceManager.GetString("StartUpWizard_startButton_Click__PasswordAndConfirmationNotMatchingOrOneIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  جاري إنشاء قاعدة البيانات ....
        /// </summary>
        internal static string StartUpWizard_startButton_Click_BuildingDatabase {
            get {
                return ResourceManager.GetString("StartUpWizard_startButton_Click_BuildingDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم السري للبرنامج غير صحيح.
        /// </summary>
        internal static string StartUpWizard_startButton_Click_IncorrectSerial {
            get {
                return ResourceManager.GetString("StartUpWizard_startButton_Click_IncorrectSerial", resourceCulture);
            }
        }
    }
}
